### ISSUE TITLE
Investigate adding GraphiQL

### ISSUE THREAD

**Issue by thelordoftheboards** [codefoundries/isomorphic-material-relay-starter-kit#82]
The following article describes some of the advantages: https://medium.com/@clayallsopp/graphiql-graphql-s-killer-app-9896242b2125#.mb99bmx7v

**Comment by thelordoftheboards** [comment]
Whenever I include GraphiQL I get:

```
/isomorphic-material-relay-starter-kit/node_modules/codemirror/lib/codemirror.js:24
  var userAgent = navigator.userAgent;
                  ^

ReferenceError: navigator is not defined
    at /Users/alex/Documents/Projects/isomorphic-material-relay-starter-kit/node_modules/codemirror/lib/codemirror.js:24:19
    at userAgent (/Users/alex/Documents/Projects/isomorphic-material-relay-starter-kit/node_modules/codemirror/lib/codemirror.js:12:22)

    at Object.<anonymous> (/Users/alex/Documents/Projects/isomorphic-material-relay-starter-kit/node_modules/codemirror/lib/codemirror.js:17:3)
    at Module._compile (module.js:425:26)
    at Module._extensions..js (module.js:432:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/alex/Documents/Projects/isomorphic-material-relay-starter-kit/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at Module.prototype.require (/Users/alex/Documents/Projects/isomorphic-material-relay-starter-kit/node_modules/isomorphic-relay/lib/fixFetch.js:20:28)
```

At this point I can not justify spending more time on this, but if anyone knows how to resolve it ...

**Comment by thelordoftheboards** [comment]
I am giving up on the browser hosted within the app and just providing links to graphiql. That means anonymous browsing at this point.
